## => Site Settings
##############################
text_skin: default
highlight_theme: default
url     : https://hakam.my.id
baseurl : /
title   : Hakam
tagline : under construction!
image   : /assets/images/hakam.jpg
description: >
  Hey there! My name is Hakam. This site is my personal blog. Sometimes I will post some of my thoughts here and I hope you enjoy reading it.
 
 
## => Language and Timezone
##############################
lang: id
timezone: Asia/Jakarta


## => Author and Social
##############################
author:
  type      : person
  name      : Hakam
  url       : /
  avatar    : /assets/images/hakam.jpg
  bio       : >
    Hey there! My name is Hakam. This site is my personal blog. Sometimes I will post some of my thoughts here and I hope you enjoy reading it.
  email     : hakam_@merahputih.id
  github    : nurhakam
  instagram : syaifulnurh


## => GitHub Repository
##############################
repository: nurhakam/nurhakam.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive/" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: default


## => Comments
##############################
comments:
  provider: gitalk
  gitalk:
    clientID    : 3a5f10fca33f48bfe2d7
    clientSecret: 7c5613d4cae778d498d0021f58cd9247be548c05
    repository  : nurhakam.github.io
    owner       : nurhakam
    admin:
      - nurhakam
      

## => Search
##############################
search:
  provider: default


## => Webmaster Verifications
##############################
webmaster_verifications:
    google: b-KdCxvA9LFa2Msq0m9VwS_jp0Qh0iHo4VGsXBF6VTM


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id : UA-52999293-5
    anonymize_ip: false


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : none

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - jekyll-text-theme.gemspec
  - /vendor


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      aside:
        toc: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag